const titles={
    ApplicationTitle:'موبو ویزیت',
    ShowAll:'مشاهده همه',
    BestExperts:'محبوب ترین ها',
    Category:'دسته بندی ها',
    CanNotGetAppointment:'عدم امکان نوبت گیری',
    CanNotGetAppointmentDescription:'در حال حاضر امکان دریافت نوبت وجود ندارد',
    AppointmentTime:'زمان حضور',
    AppointmentTimes:'ساعات ملاقات',
    AppointmentNumber:'شماره',
    ActiveDates:'روزهای فعال',
    CanNotLogin:'خطا در ورود به سیستم',
    CanNotLoginDescription:'نام کاریری یا کلمه عبور اشتباه می باشد',
    Mobile:'شماره موبایل',
    MobileSample:'0912',
    Password:'کلمه عبور',
    PasswordAgain:'تکرار کلمه عبور',
    CurrentPassword:'کلمه عبور فعلی',
    NewPassword:'کلمه عبور جدید',
    Token:'شناسه',
    Error:'خطا',
    Info:'پیام',
    MobileRegisteredError:'شماره موبایل قبلا ثبت شده است',
    MobileIsRequired:'ثبت شماره موبایل اجباری است',
    PasswordIsRequired:'ثبت کلمه عبور اجباری است',
    OTPIsRequired:'ثبت شناسه یکبار مصرف اجباری است',
    AlreadyExistOTPError:'شناسه یکبار مصرف قبلا ارسال شده است',
    OTPIsInvalid:'َشناسه یکبار مصرف اشتباه است',
    UnknownErorr:'َخطایی رخ داده است',
    UserOrPasswordInvalid:'شماره موبایل یا کلمه عبور اشتباه است',
    PasswordAgainIsRequired:'ثبت تکرار کلمه عبور اجباری است',
    MobileIncorrect:'شماره موبایل اشتباه است',
    PasswordsIsNotSame:'کلمه ی عبور اول و دوم مشابه نیستند',
    NameIsRequired:'ثبت (نام) اجباری است',
    FamilyIsRequired:'ثبت (نام خانوادگی) اجباری است',
    AppointmentBeforSet:'این زمان ملاقات قبلا رزرو شده است',
} 

export default titles;